
name: preppro
description: PrepPro — Mobile Blue-Pro (Patched)
publish_to: "none"
version: 1.0.2+3

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  go_router: ^14.2.1
  shared_preferences: ^2.2.3
  google_fonts: ^5.0.0
  fl_chart: ^1.1.1
  sentry_flutter: ^9.10.0
  firebase_core: ^4.4.0
  firebase_auth: ^6.1.4
  cloud_firestore: ^6.1.2
  provider: ^6.0.0
  package_info_plus: ^8.0.2
  intl: ^0.20.2
  share_plus: ^10.0.2
  google_mobile_ads: ^6.0.0
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_native_splash: ^2.4.1
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/data/preppro_500_recipes.json
    - assets/data/preppro_625_recipes.json
    - assets/images/logo_preppro_blue.png
    - assets/images/logo_icon_foreground.png
    - assets/images/PrepProBlue.png
    - assets/images/recipes/
