// File generated by flutterfire_cli.
// This file contains Firebase configuration for the app.
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBiOg3Maef2QU_0aAjXGJkpmGHGNc76AH8',
    appId: '1:235971954780:web:abcdefghijklmnop',
    messagingSenderId: '235971954780',
    projectId: 'preppro-2f5bc',
    authDomain: 'preppro-2f5bc.firebaseapp.com',
    storageBucket: 'preppro-2f5bc.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBiOg3Maef2QU_0aAjXGJkpmGHGNc76AH8',
    appId: '1:235971954780:android:7198ca430444dd6b90fe99',
    messagingSenderId: '235971954780',
    projectId: 'preppro-2f5bc',
    storageBucket: 'preppro-2f5bc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBiOg3Maef2QU_0aAjXGJkpmGHGNc76AH8',
    appId: '1:235971954780:ios:abcdefghijklmnop',
    messagingSenderId: '235971954780',
    projectId: 'preppro-2f5bc',
    storageBucket: 'preppro-2f5bc.firebasestorage.app',
    iosBundleId: 'com.preppro.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBiOg3Maef2QU_0aAjXGJkpmGHGNc76AH8',
    appId: '1:235971954780:macos:abcdefghijklmnop',
    messagingSenderId: '235971954780',
    projectId: 'preppro-2f5bc',
    storageBucket: 'preppro-2f5bc.firebasestorage.app',
    iosBundleId: 'com.preppro.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBiOg3Maef2QU_0aAjXGJkpmGHGNc76AH8',
    appId: '1:235971954780:windows:abcdefghijklmnop',
    messagingSenderId: '235971954780',
    projectId: 'preppro-2f5bc',
    storageBucket: 'preppro-2f5bc.firebasestorage.app',
  );
}
