// File generated by flutterfire_cli.
// This file contains Firebase configuration for the app.
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    return web;
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZN6JGGXqNKqJhQKzWLl-XXXXXXXXXXXXXX', // Replace with your web API key
    appId: '1:123456789:web:abcdefghijklmnop',
    messagingSenderId: '123456789',
    projectId: 'preppro-meal-planner',
    authDomain: 'preppro-meal-planner.firebaseapp.com',
    storageBucket: 'preppro-meal-planner.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZN6JGGXqNKqJhQKzWLl-XXXXXXXXXXXXXX', // Replace with your Android API key
    appId: '1:123456789:android:abcdefghijklmnop',
    messagingSenderId: '123456789',
    projectId: 'preppro-meal-planner',
    storageBucket: 'preppro-meal-planner.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZN6JGGXqNKqJhQKzWLl-XXXXXXXXXXXXXX', // Replace with your iOS API key
    appId: '1:123456789:ios:abcdefghijklmnop',
    messagingSenderId: '123456789',
    projectId: 'preppro-meal-planner',
    storageBucket: 'preppro-meal-planner.appspot.com',
    iosBundleId: 'com.example.preppro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBZN6JGGXqNKqJhQKzWLl-XXXXXXXXXXXXXX', // Replace with your macOS API key
    appId: '1:123456789:macos:abcdefghijklmnop',
    messagingSenderId: '123456789',
    projectId: 'preppro-meal-planner',
    storageBucket: 'preppro-meal-planner.appspot.com',
    iosBundleId: 'com.example.preppro',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBZN6JGGXqNKqJhQKzWLl-XXXXXXXXXXXXXX', // Replace with your Windows API key
    appId: '1:123456789:windows:abcdefghijklmnop',
    messagingSenderId: '123456789',
    projectId: 'preppro-meal-planner',
    storageBucket: 'preppro-meal-planner.appspot.com',
    apiKeyId: 'your-api-key-id',
  );
}
